apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-core
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: kubernetes-cluster-manifests
  path: ./infrastructure/core
  prune: true
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: kiali-operator
      namespace: istio-system
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: fluent-bit
      namespace: logging
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-configuration
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-core
  sourceRef:
    kind: GitRepository
    name: kubernetes-cluster-manifests
  path: ./infrastructure/configuration
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-configuration
  sourceRef:
    kind: GitRepository
    name: kubernetes-cluster-manifests
  path: ./apps
  prune: true
  validation: client