apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: service3-helmrelease
  namespace: service3
spec:
  interval: 10m
  releaseName: service3
  chart:
    spec:
      # The path of the chart relative to the repository root
      chart: ./apps/service3/charts/service3
      # The reference to the GitRepository
      sourceRef:
        kind: GitRepository
        name: kubernetes-cluster-manifests
        # Optional, defaults to the namespace of the HelmRelease
        namespace: flux-system
  values:
    image:
      repository: azure-acr.azurecr.io/service3 # {"$imagepolicy": "flux-system:service3-image-policy:name"}
      tag: "master-716ec05-1652354361" # {"$imagepolicy": "flux-system:service3-image-policy:tag"}
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
    podLabels:
      version: v1
    podAnnotations:
      ## Set one resource override and the rest will be limitless, otherwise they all will be default.
      ## (proxyCPU/proxyCPULimit/proxyMemory/proxyMemoryLimit).
      sidecar.istio.io/proxyCPU: 10m
