# Latest version:
# https://artifacthub.io/packages/helm/cert-manager/cert-manager
#
# CustomResourceDefinitions required!
#
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.8.1
      sourceRef:
        kind: HelmRepository
        name: cert-manager-helm-repository
        namespace: cert-manager
  values:
    installCRDs: false # manage crds manually
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cert-manager-helm-repository
  namespace: cert-manager
spec:
  interval: 10m
  url: https://charts.jetstack.io