apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: replace-image-registry
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/title: Replace Image Registry
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: 1.5.4
    policies.kyverno.io/description: >-
      Enforce our own cache registry for public images.
spec:
  background: true
  rules:
    - name: replace-image-registry-pod-containers
      match:
        resources:
          kinds:
          - Pod
      mutate:
        foreach:
        - list: "request.object.spec.containers"
          patchStrategicMerge:
            spec:
              containers:
              - name: "{{ element.name }}"
                image: |-    
                  {{ regex_replace_all('^(?:(?:public\.)?(?:docker|ghcr|quay|ecr)*?\.\S*?/)?([^\.]+:.+)$', '{{element.image}}', '' )}}
    - name: replace-image-registry-pod-initcontainers
      match:
        resources:
          kinds:
          - Pod
      preconditions:
        all:
        - key: "{{ request.object.spec.initContainers[] || '' | length(@) }}"
          operator: GreaterThanOrEquals
          value: 1
      mutate:
        foreach:
        - list: "request.object.spec.initContainers"
          patchStrategicMerge:
            spec:
              initContainers:
              - name: "{{ element.name }}"
                image: |-    
                  {{ regex_replace_all('^(?:(?:public\.)?(?:docker|ghcr|quay|ecr)*?\.\S*?/)?([^\.]+:.+)$', '{{element.image}}', '' )}}
    - name: replace-image-registry-depl-containers
      match:
        resources:
          kinds:
          - Deployment
      mutate:
        foreach:
        - list: "request.object.spec.template.spec.containers"
          patchStrategicMerge:
            spec:
              template:
                spec:
                  containers:
                  - name: "{{ element.name }}"
                    image: |-    
                      {{ regex_replace_all('^(?:(?:public\.)?(?:docker|ghcr|quay|ecr)*?\.\S*?/)?([^\.]+:.+)$', '{{element.image}}', '' )}}
    - name: replace-image-registry-depl-initcontainers
      match:
        resources:
          kinds:
          - Deployment
      preconditions:
        all:
        - key: "{{ request.object.spec.template.spec.initContainers[] || '' | length(@) }}"
          operator: GreaterThanOrEquals
          value: 1
      mutate:
        foreach:
        - list: "request.object.spec.template.spec.initContainers"
          patchStrategicMerge:
            spec:
              template:
                spec:
                  initContainers:
                  - name: "{{ element.name }}"
                    image: |-    
                      {{ regex_replace_all('^(?:(?:public\.)?(?:docker|ghcr|quay|ecr)*?\.\S*?/)?([^\.]+:.+)$', '{{element.image}}', '' )}}