# Latest chart: 
# https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/Chart.yaml
# Latest version (tag)
# https://fluentbit.io/announcements/
#
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: logging
spec:
  interval: 10m
  releaseName: fluent-bit
  chart:
    spec:
      chart: fluent-bit
      version: 0.19.22
      sourceRef:
        kind: HelmRepository
        name: fluent-bit-helm-repository
        namespace: logging
  values:

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: fluent-bit-helm-repository
  namespace: logging
spec:
  interval: 10m
  url: https://fluent.github.io/helm-charts