apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 10m
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      version: v2.3.3
      sourceRef:
        kind: HelmRepository
        name: kyverno-helm-repository
        namespace: kyverno
  values:
    resources:
      limits:
        memory: 640Mi
      requests:
        memory: 512Mi
    replicaCount: 3
    serviceMonitor:
      enabled: true
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kyverno-helm-repository
  namespace: kyverno
spec:
  interval: 10m
  url: https://kyverno.github.io/kyverno/